name: Run Unit Tests

on:
  pull_request:
    branches:
      - main

env:
  UV_SYSTEM_PYTHON: 1
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.4"
          enable-cache: true
          cache-dependency-glob: |
            pyproject.toml
      - name: Install dependencies
        run: |
          uv pip install -e libs/creative-assistant/
          uv pip install pytest
      - name: Run tests with pytest
        run: pytest libs/creative-assistant/tests/unit
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Setup uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.5.4"
          enable-cache: true
          cache-dependency-glob: |
            pyproject.toml
      - name: Install dependencies
        run: |
          uv pip install -e libs/creative-assistant/
          uv pip install ruff
      - name: Run linter with ruff
        run: uvx ruff check libs/creative-assistant
